import os
import json
from typing import Dict, Any
from dotenv import load_dotenv

# We import these conditionally or wrap them to avoid crash if installation hasn't finished
try:
    from langchain_google_genai import ChatGoogleGenerativeAI
    from langchain_core.prompts import ChatPromptTemplate
except ImportError:
    ChatGoogleGenerativeAI = None
    ChatPromptTemplate = None

load_dotenv()

class InvestigatorAgent:
    def __init__(self, model_name="gemini-1.5-flash"):
        api_key = os.getenv("GOOGLE_API_KEY")
        if not api_key or not ChatGoogleGenerativeAI:
            self.llm = None
            if not api_key:
                print("WARNING: GOOGLE_API_KEY not found. Agent will run in Simulation Mode.")
            if not ChatGoogleGenerativeAI:
                print("WARNING: langchain-google-genai not installed. Agent will run in Simulation Mode.")
        else:
            self.llm = ChatGoogleGenerativeAI(model=model_name, google_api_key=api_key)
            
        self.system_prompt = """
        You are a Tier-3 Senior SOC Analyst specialized in hybrid AI threat detection.
        Your task is to 'Investigate' a security alert generated by our Chrono-SOC pipeline.
        
        The pipeline uses three layers:
        1. Behavioral Layer (Supervised RF): Detects patterns similar to known Account Takeovers (ATO).
        2. Graph Anomaly Layer (Isolation Forest): Detects shifts in device/IP/User relationship graphs.
        3. Rule Engine: Hard-coded security best practices (e.g., country mismatches).
        
        You will receive the alert metadata in JSON format.
        Provide a concise, professional, and actionable 'Analyst Report' that:
        - Interprets the risk scores (Why did it flag?).
        - Correlates the features (e.g., Device change + Country change).
        - Provides a 'Final Verdict' (True Positive / False Positive / Suspicious).
        - Suggests a 'Remediation Action' (Reset MFA, Block IP, or Monitor).
        
        Tone: Professional, Data-Driven, Decisive.
        Output Format: A single well-structured paragraph or a brief bulleted summary (max 200 words).
        """

    def investigate(self, alert_data: Dict[str, Any]) -> str:
        if not self.llm:
            return self._shim_investigation(alert_data)
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", self.system_prompt),
            ("human", "Investigate this alert: {alert_json}")
        ])
        
        chain = prompt | self.llm
        try:
            response = chain.invoke({"alert_json": json.dumps(alert_data, indent=2)})
            return response.content
        except Exception as e:
            return f"Agent Investigation Error: {str(e)}"

    def _shim_investigation(self, alert_data: Dict[str, Any]) -> str:
        # Fallback simulation if no API key is present
        risk = alert_data.get('final_risk', alert_data.get('final_score', 0))
        user = alert_data.get('User ID', 'Unknown')
        reason = alert_data.get('reason_codes', alert_data.get('reason_tags', 'Behavioral Anomaly'))
        
        if risk > 0.8:
            return f"[SIMULATED REPORT] CRITICAL: User {user} exhibits high-confidence exploit markers. Risk score of {risk:.2f} driven by layered flags: {reason}. Pattern matches known credential stuffing with subsequent lateral movement. ACTION: Immediate suspension and MFA rotation."
        return f"[SIMULATED REPORT] SUSPICIOUS: User {user} triggered behavioral thresholds ({risk:.2f}). Detection based on: {reason}. IP/ASN behavior is unusual but not definitive for ATO. ACTION: Flag for 24h surveillance and step-up auth on next login."

if __name__ == "__main__":
    # Test simulation
    agent = InvestigatorAgent()
    mock_alert = {
        "User ID": "12345",
        "final_risk": 0.89,
        "reason_codes": "COUNTRY_MISMATCH;DEVICE_NOVELTY",
        "Country": "RU",
        "IP Address": "1.2.3.4"
    }
    print(agent.investigate(mock_alert))
